markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [fenced_code_blocks, autolink, tables, strikethrough]

name: Kenyon Duan
url: http://kenyonduan.github.io/
description:
twitter: kenyonduan
weibo:	kenyonduan
