markdown: rdiscount
highlighter: pygments
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Kenyon Duan
url: http://kenyonduan.github.io/
description:
twitter: kenyonduan
weibo:	kenyonduan